const IDS=["freeturn","mieru","free_pool"];
const NAMES={freeturn:"FreeTurn",mieru:"Mieru",free_pool:"Подборка"};
const LABELS={ok:"Работает",warning:"Нестабильно",down:"Недоступно",unknown:"Нет данных"};
const RANK={unknown:0,ok:1,warning:2,down:3};
const MAX_AGE=15*60*1000;
let samples=[];
let month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let selectedDay=null;
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n}
function dayKey(time){const d=new Date(time);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function dayStates(){const days=new Map();for(const row of samples){const key=dayKey(row[0]*1000);const current=days.get(key)||["unknown","unknown","unknown"];for(let i=0;i<3;i++)if(RANK[row[i+1]]>RANK[current[i]])current[i]=row[i+1];days.set(key,current)}return days}
function renderOverall(data){const checked=new Date(data?.checked_at||0);const fresh=checked.getTime()>0&&Math.abs(Date.now()-checked.getTime())<=MAX_AGE;document.querySelector("#checked-at").textContent=checked.getTime()>0?checked.toLocaleString("ru-RU",{dateStyle:"medium",timeStyle:"short"}):"нет данных";const states=fresh?IDS.map(id=>data?.services?.[id]?.state||"unknown"):["unknown"];let state="ok",title="Все системы работают",detail="Последние проверки завершились успешно.";if(states.includes("down")){state="down";title="Есть недоступные системы";detail="Мы видим сбой по одной или нескольким проверкам."}else if(states.includes("warning")||states.includes("unknown")){state="warning";title="Некоторые системы требуют внимания";detail="Есть нестабильность или недостаточно данных для подтверждения."}if(!fresh){state="unknown";title="Нет свежих данных";detail="Последние результаты проверки устарели. Повторите попытку позже."}document.querySelector("#overall").className=`overall ${state}`;document.querySelector("#overall-title").textContent=title;document.querySelector("#overall-detail").textContent=detail;return fresh}
function renderSystems(data,fresh,days){const host=document.querySelector("#systems");host.replaceChildren();const today=new Date();for(let i=0;i<IDS.length;i++){const id=IDS[i],item=fresh?data?.services?.[id]:null,state=LABELS[item?.state]?item.state:"unknown";const section=el("article","service");const top=el("div","service-top");top.append(el("span",`state-icon ${state}`,state==="ok"?"✓":state==="down"?"×":state==="warning"?"!":"?"),el("span","service-name",NAMES[id]),el("span","service-status",LABELS[state]));const recent=samples.filter(row=>row[0]*1000>=Date.now()-90*86400000&&row[i+1]!=="unknown");const uptime=recent.length>=100&&recent.at(-1)[0]-recent[0][0]>=86400?`${(100*recent.filter(r=>r[i+1]==="ok").length/recent.length).toFixed(1)}% за 90 дней`:"История собирается";top.append(el("span","uptime",uptime));section.append(top);const bars=el("div","bars");bars.setAttribute("aria-label",`История ${NAMES[id]} за 90 дней`);for(let n=89;n>=0;n--){const d=new Date(today.getFullYear(),today.getMonth(),today.getDate()-n);const key=dayKey(d),s=days.get(key)?.[i]||"unknown";const bar=el("span",`bar ${s}`);bar.title=`${d.toLocaleDateString("ru-RU")}: ${LABELS[s]}`;bars.append(bar)}section.append(bars,el("p","service-summary",item?.summary||"Нет свежих результатов проверки."));host.append(section)}}
function overallDay(states){if(!states)return"unknown";if(states.includes("down"))return"down";if(states.includes("warning"))return"warning";if(states.includes("ok"))return"ok";return"unknown"}
function renderCalendar(days){const label=document.querySelector("#month-label");label.textContent=month.toLocaleDateString("ru-RU",{month:"long",year:"numeric"});document.querySelector("#month-next").disabled=month.getFullYear()===new Date().getFullYear()&&month.getMonth()===new Date().getMonth();const grid=document.querySelector("#calendar");grid.replaceChildren();const offset=(month.getDay()+6)%7;const start=new Date(month.getFullYear(),month.getMonth(),1-offset);for(let n=0;n<42;n++){const d=new Date(start.getFullYear(),start.getMonth(),start.getDate()+n),key=dayKey(d),states=days.get(key),state=overallDay(states);const button=el("button",`day ${d.getMonth()===month.getMonth()?"":"other"} ${key===dayKey(new Date())?"today":""} ${key===selectedDay?"selected":""}`,String(d.getDate()));button.type="button";button.setAttribute("aria-label",`${d.toLocaleDateString("ru-RU")}: ${LABELS[state]}`);button.append(el("i",state));button.addEventListener("click",()=>{selectedDay=key;document.querySelector("#day-detail").textContent=`${d.toLocaleDateString("ru-RU",{dateStyle:"long"})}: ${states?IDS.map((id,i)=>`${NAMES[id]} — ${LABELS[states[i]]}`).join(" · "):"данных за этот день нет"}`;renderCalendar(days)});grid.append(button)}}
function renderEvents(){const host=document.querySelector("#events");host.replaceChildren();let events=[];for(let n=1;n<samples.length;n++){const a=samples[n-1],b=samples[n];if(b[0]-a[0]>900)continue;for(let i=0;i<3;i++){if(a[i+1]!==b[i+1]&&a[i+1]!=="unknown"&&b[i+1]!=="unknown")events.push({time:b[0],name:NAMES[IDS[i]],state:b[i+1]})}}events=events.slice(-12).reverse();if(!events.length){host.append(el("p","empty","Пока нет зарегистрированных изменений. История накапливается с момента запуска страницы."));return}for(const event of events){const row=el("div","event");row.append(el("time","",new Date(event.time*1000).toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"})),el("p","",`${event.name}: ${LABELS[event.state].toLowerCase()}`));host.append(row)}}
async function refresh(){let data=null,history=null;try{const response=await fetch(`status.json?t=${Date.now()}`,{cache:"no-store"});if(response.ok)data=await response.json()}catch{}try{const response=await fetch(`history.json?t=${Date.now()}`,{cache:"no-store"});if(response.ok)history=await response.json()}catch{}samples=Array.isArray(history?.samples)?history.samples.filter(row=>Array.isArray(row)&&row.length===4&&Number.isFinite(row[0])&&row.slice(1).every(s=>LABELS[s])).sort((a,b)=>a[0]-b[0]):[];const fresh=renderOverall(data),days=dayStates();renderSystems(data,fresh,days);renderCalendar(days);renderEvents()}
document.querySelector("#month-prev").addEventListener("click",()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar(dayStates())});document.querySelector("#month-next").addEventListener("click",()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar(dayStates())});
refresh();setInterval(refresh,60000);
